### ISSUE TITLE
Inconsistent allele column names

### ISSUE THREAD

**Issue by SamuelSun2000** [cumc/pecotmr#101]
Some places in the package we use A1 and A2. Others we use A0 and A1. We should unify them

**Comment by gaow** [comment]
@SamuelSun2000 is this addressed now? if so, please close the ticket. Thanks!

**Comment by SamuelSun2000** [comment]
@gaow Yes fixed now, that one was a obvious typo that I somehow accidentaly deleted and added back. Thanks for pointing out!
