### ISSUE TITLE
handle_invalid_summary_stat function is missing

### ISSUE THREAD

**Issue by rfeng2023** [cumc/pecotmr#242]
I am trying to investigate mash preprocessing while there is an error showing 
> `Error in handle_invalid_summary_stat(batch_combined_data, bhat = paste0(cond, : could not find function "handle_invalid_summary_stat"` 

And I can not find the definition of it in the current version in repo. That error happened after pecotmr version  ‘0.1.62’, till  ‘0.1.66’

**Comment by gaow** [comment]
Sorry apparently it is renamed: https://github.com/cumc/pecotmr/blob/main/R/mash_wrapper.R#L2
